# Generated by Django 3.2.5 on 2021-07-13 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='contact',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='contact',
            name='contact',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(max_length=50),
        ),
        migrations.AlterField(
            model_name='contact',
            name='feedback',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='customer',
            name='zipcode',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='profile',
            name='contact',
            field=models.PositiveIntegerField(),
        ),
    ]
