# Generated by Django 3.2.5 on 2021-07-14 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_profile_dob'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='dob',
        ),
    ]
