# Generated by Django 3.2.5 on 2021-07-14 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_profile_dob'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='dob',
        ),
    ]
