# Generated by Django 3.2.5 on 2021-07-14 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_remove_profile_dob'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
