# Generated by Django 3.2.5 on 2021-07-16 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_profile_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('M', 'Mobile'), ('L', 'Laptop'), ('C', 'Camera'), ('MTS', 'Mens Tshirt'), ('MS', 'Mens Shirt'), ('MJ', 'Mens Jeans'), ('MSU', 'Mens Suit'), ('MW', 'Mens Watch'), ('MSH', 'Mens Shoes'), ('WTS', 'Womens Tshirt'), ('WJ', 'Womens Jeans'), ('WK', 'Womens Kurti'), ('WSA', 'Womens Saree'), ('WW', 'Womens Watch'), ('WSH', 'Womens Shoes')], max_length=4),
        ),
    ]
