# Generated by Django 3.2.5 on 2021-07-17 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderplaced',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
